# Generated by Django 5.0.6 on 2024-07-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=300, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='hash',
            field=models.CharField(max_length=256),
        ),
    ]
