# Generated by Django 5.0.6 on 2024-07-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_uploadedfile_file_alter_uploadedfile_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Disasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=64)),
                ('data', models.CharField(max_length=64)),
                ('addr', models.CharField(max_length=64)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.function'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uploadedfile')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
